### ISSUE TITLE
Roblox-Username-Checker is not working at all.

### ISSUE THREAD

**Issue by SoMuchEase** [Dew3/Roblox-Username-Checker#3]
Hi, the Roblox-Username-Checker is not working at all in both python 3.9.0 version and last version of python (python 3.10.4).
I installed everything and followed the steps of putting the usernames in Usernames.txt but it's still not working.
I used:
pip3 install robloxapi
pip3 install asyncio
pip3 install requests
pip3 install pathlib
pip3 install colorama

Here the error message on launching Main.py : 
`←[90m[←[36m+←[90m]Dew3's Roblox Username Checker
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Desktop\Roblox-Username-Checker-main\Main.py", line 59, in <module>
    asyncio.run(check())
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Utilisateur\Desktop\Roblox-Username-Checker-main\Main.py", line 47, in check
    user = await client.get_user_by_username(username) #robloxapi either returns a user object or None if the user doesn't exist
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\robloxapi\client.py", line 71, in get_user_by_username
    r = await self.request.request(url=f'https://api.roblox.com/users/get-by-username?username={roblox_name}', method="GET", noerror=True)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\robloxapi\utils\request.py", line 49, in request
    r = await self.requests.request(kwargs['method'], kwargs['url'], headers=self.headers, cookies=self.cookies, data=kwargs.get('data'))
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\client.py", line 541, in request
    response = await self.send(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\client.py", line 140, in send
    response = await self.send_handling_redirects(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\client.py", line 177, in send_handling_redirects
    response = await self.dispatch.send(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\dispatch\connection_pool.py", line 130, in send
    raise exc
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\dispatch\connection_pool.py", line 120, in send
    response = await connection.send(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\dispatch\connection.py", line 53, in send
    await self.connect(verify=verify, cert=cert, timeout=timeout)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\dispatch\connection.py", line 81, in connect
    reader, writer, protocol = await self.backend.connect(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\http3\concurrency.py", line 204, in connect
    stream_reader, stream_writer = await asyncio.wait_for(  # type: ignore
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1110, in _create_connection_transport
    await waiter
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 631, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 676, in _process_write_backlog
    ssldata = self._sslpipe.do_handshake(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 116, in do_handshake
    self._sslobj = self._context.wrap_bio(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 526, in wrap_bio
    return self.sslobject_class._create(
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 865, in _create
    sslobj = context._wrap_bio(
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)

**Comment by qsels** [comment]
something happened the robloxapi where when you try to use it more than 2 times in the span of around 40 seconds it errors.
